# Generated by Django 2.2.5 on 2020-01-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstuff', '0004_auto_20200112_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilePictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
