# Generated by Django 2.2.5 on 2019-09-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Жанр не указан', max_length=100, verbose_name='Жанор')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Издатель', max_length=200, verbose_name='Издатель')),
                ('summary', models.TextField(help_text='Описание издателя')),
                ('foundation_date', models.DateField(verbose_name='Год основания')),
            ],
        ),
        migrations.CreateModel(
            name='SysReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HDD', models.CharField(help_text='Место на жестком диске', max_length=300, verbose_name='Место на жестком диске')),
                ('CPU', models.CharField(help_text='Процессор', max_length=300, verbose_name='Рекоментуемый процессор')),
                ('GPU', models.CharField(help_text='Видеокарта', max_length=300, verbose_name='Рекоментуемая видеокарта')),
                ('DDR', models.SmallIntegerField(help_text='Объем оперативной памяти (Гб)', verbose_name='Объем оперативной памяти (Гб)')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название игры', max_length=200, verbose_name='Название игры')),
                ('summary', models.TextField(default='Нет описания', help_text='Описание игры', verbose_name='Описание игры')),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0, help_text='Цена игры', max_length=9999.0, verbose_name='Цена')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='gamePages/')),
                ('scoreCritics', models.IntegerField(help_text='Средняя оценка критиков')),
                ('scoreUsers', models.IntegerField(help_text='Средняя оценка пользователей')),
                ('genre', models.ManyToManyField(to='the_boythesda.Genre', verbose_name='Жанр(ы)')),
                ('publisher', models.ForeignKey(default='Издатель отсутствует или был удален', help_text='Издатель', on_delete=django.db.models.deletion.SET_DEFAULT, to='the_boythesda.Publisher')),
                ('sysReq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_boythesda.SysReq', verbose_name='Системные требования (Рекомендуемые)')),
            ],
            options={
                'verbose_name': 'Игра',
            },
        ),
    ]
