# Generated by Django 2.2.5 on 2019-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_boythesda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysreq',
            name='configuration_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
