# Generated by Django 2.2.5 on 2019-10-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_boythesda', '0002_sysreq_configuration_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='Game',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='Genre',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='Publisher',
        ),
        migrations.AlterModelTable(
            name='sysreq',
            table='SysReq',
        ),
    ]
