# Generated by Django 2.2.5 on 2019-10-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_boythesda', '0003_auto_20191003_1640'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='GAME',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='GENRE',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='PUBLISHER',
        ),
        migrations.AlterModelTable(
            name='sysreq',
            table='SYSREQ',
        ),
    ]
