# Generated by Django 2.2.5 on 2019-12-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_boythesda', '0004_auto_20191003_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scoreCritics',
            field=models.IntegerField(blank=True, help_text='Средняя оценка критиков', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='scoreUsers',
            field=models.IntegerField(blank=True, help_text='Средняя оценка пользователей', null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='Жанр не указан', max_length=100, verbose_name='Жанр'),
        ),
    ]
