# Generated by Django 2.2.5 on 2019-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_boythesda', '0006_auto_20191230_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='foundation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Год основания'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='summary',
            field=models.TextField(blank=True, default='Нет описания', help_text='Описание издателя', null=True),
        ),
    ]
