# Generated by Django 2.2.5 on 2020-01-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_boythesda', '0008_auto_20200119_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Издатель', max_length=200, unique=True, verbose_name='Издатель'),
        ),
    ]
